name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt update && sudo apt install libmosquitto-dev libbsd-dev wiringpi libyaml-dev libwiringpi-dev
    - name: make
      run: cd mqtt_rpi && make

